// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8drhxaOPXe_Fw5v073J0kbnkbsJG6SU0',
    appId: '1:436750044889:web:0e9bd2eda285d74780b8c8',
    messagingSenderId: '436750044889',
    projectId: 'new-chat-app-b803e',
    authDomain: 'new-chat-app-b803e.firebaseapp.com',
    storageBucket: 'new-chat-app-b803e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAok5f6rom4Tuq069_LGGDVFir8TPHv4t8',
    appId: '1:436750044889:android:4942c53b1644c8e380b8c8',
    messagingSenderId: '436750044889',
    projectId: 'new-chat-app-b803e',
    storageBucket: 'new-chat-app-b803e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUpko39g3HNvENTsctfu3YxdJvsgdl9UU',
    appId: '1:436750044889:ios:697439e0eb121b1c80b8c8',
    messagingSenderId: '436750044889',
    projectId: 'new-chat-app-b803e',
    storageBucket: 'new-chat-app-b803e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
